repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: check-added-large-files
  - repo: https://github.com/opensource-nepal/commitlint
    rev: v1.2.0
    hooks:
    - id: commitlint