---
blank_issues_enabled: false
contact_links:
  - name: Alpha McBottington Community Support
    url: https://github.com/mobilemike/alpha/discussions
    about: Please ask and answer questions here.
